#-----------------------------------------------------------------------------#
#
# Top level tests
#
#-----------------------------------------------------------------------------#
CompileAll:
  script:
    - nix-shell --run './compile_all.sh'
  tags: ["freertos"]