language: c

notifications:
  email: false

services:
  - docker

before install:
  - docker pull galoisinc/besspin:cheri

script:
  - docker run -v ${TRAVIS_BUILD_DIR}:/FreeRTOS-mirror galoisinc/besspin:cheri /bin/bash -c "cd /FreeRTOS-mirror; ./compile_all.sh"
